"plugins": [
  "remark-stringify",
  "preset-lint-markdown-style-guide",
  "lint-list-item-spacing",
  "remark-preset-lint-markdown-style-guide",
  ["lint-list-item-indent", "mixed"],
  ["lint-unordered-list-marker-style", "*"],
  ["remark-lint-emphasis-marker", false],
]
