language: c 

sudo: required

services:
- docker

script:
 - cp -vr docker ${HOME}
 - cd ../../
 - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
 - cp -r $HOME/.ccache ${HOME}/docker/ccache
 - docker build  ${TRAVIS_TAG:+-t votca/votca:${TRAVIS_TAG}}
                 -t votca/votca:latest -t votca/votca:${TRAVIS_BRANCH} ${HOME}/docker/ &&
   rm -rf $HOME/.ccache &&
   CON=$(docker run -d votca/votca:${TRAVIS_BRANCH} /bin/bash) &&
   docker cp ${CON}:/home/votca/.ccache ${HOME}/

after_success:
  - shopt -s extglob && [[ ${TRAVIS_BRANCH} = @(master|stable|v1.*) ]] && DEPLOY=yes
  - if [[ ${TRAVIS_BRANCH} = master ]]; then DOCKER_TAG=latest; else DOCKER_TAG="${TRAVIS_BRANCH}"; fi
  - if [[ ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${DEPLOY} ]]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push "votca/votca:${DOCKER_TAG}";
    fi

cache:
  - ccache

notifications:
  email:
    - votca-commits@googlegroups.com 
