#the original source of this file can be found in tools repository change it ther
# changes in tools|csg tiggered a full rebuild
# changes in csgapps|csg-manual|csg-tutorials only trigger tools+csg+ifself

language: cpp

sudo: false

addons:
  apt:
    sources:
      - boost-latest 
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - ccache
      - gcc-4.8
      - g++-4.8
      - libfftw3-dev
      - cmake
      - cmake-data
      - libgsl0-dev
      - txt2tags
      - libboost1.55-all-dev
      - libexpat1-dev
      - libsqlite3-dev
      - libhdf5-serial-dev
      - pkg-config
      - pgf
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - cm-super
      - doxygen
      - graphviz
      - ghostscript
      - gnuplot-nox
      - octave

env:
  global:
    - GMX_MAX_THREADS=8
    - CCACHE_CPP2=yes #for clang
    - GVER=4.8
  matrix: #NINJA=1 is currently not support by Travis' cmake, enable when >=2.8.9
    - BDIR=build WERROR=yes J=4 TYPE=Debug
    - BDIR=build WALL=yes J=4 TYPE=Debug
    - BDIR=build WERROR=yes J=4 TYPE=Release
    - BDIR=build WALL=yes J=4 TYPE=Release MAN=yes
    - MINIMAL=yes J=4

before_script:
  - rm -vrf * .git
  - wget https://raw.githubusercontent.com/votca/buildutil/master/build.sh && chmod 755 build.sh
  - mkdir -p "$HOME/votca/src"
  - if [[ ${GMX_VERSION} = 9999 ]]; then
      CMAKE_VERSION=3.4.3-Linux-x86_64 &&
      wget --no-check-certificate -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:3}/cmake-${CMAKE_VERSION}.tar.gz | tar -xz &&
      export CMAKE="$PWD/cmake-${CMAKE_VERSION}/bin/cmake" ;
    fi
  - if [[ ${MAN} ]]; then git clone --depth=1 https://github.com/votca/doxygen.git "$HOME/votca/src/devdoc"; fi 
  - if [[ ${GVER} ]]; then export CC=gcc-${GVER}; export CXX=g++-${GVER}; fi
  - pip install --user numpy

script:
  - PATH="$HOME/hdf5:$PATH" ./build.sh -Wu --prefix "$HOME/votca"
    ${TYPE:+-DCMAKE_BUILD_TYPE=${TYPE}}
    ${TEST:+--runtest=$TEST} ${WERROR:+--warn-to-errors} -DWITH_H5MD=ON ${MINIMAL:+--minimal} ${MAN:+--devdoc}
    ${J:+-j$J} ${BDIR:+--builddir=$BDIR} ${NINJA:+--ninja} ${WALL:+--Wall} ${GMX_VERSION:+--gmx-release ${GMX_VERSION}}
    --directory "$HOME/votca/src" --no-clean --depth 1 -DGMX_USE_RDTSCP=OFF ${GMX_DOUBLE:+-DGMX_DOUBLE=yes}
    tools $([[ ${MINIMAL} ]] || echo gromacs) csg csgapps ${MAN:+csg-manual} ${TEST:+csg-tutorials}
    ${CTP:+kmc moo ctp} ${XTP:+xtp}

cache:
  - ccache

compiler:
  - gcc

notifications:
  email:
    - votca-commits@googlegroups.com 
