language: generic

sudo: required

services:
- docker

script:
 - docker build  --build-arg TRAVIS=${TRAVIS} --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH}
                 --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
                 --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
                 --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                 -t votca/votca:latest -f docker/votca docker/

after_success:
  - if [[ ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == docker ]]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push "votca/votca:latest";
    fi


notifications:
  email:
    - votca-commits@googlegroups.com 
