#the original source of this file can be found in tools repository change it ther
# changes in tools|csg tiggered a full rebuild
# changes in csgapps|csg-manual|csg-tutorials only trigger tools+csg+ifself

language: cpp

sudo: false

addons:
  apt:
    sources: boost-latest 
    packages:
      - cmake
      - ccache
      - libfftw3-dev
      - libgsl0-dev
      - txt2tags
      - libboost1.55-all-dev
      - libexpat1-dev
      - libsqlite3-dev
      - pkg-config
      - pgf
      - texlive-fonts-recommended
      - texlive-latex-extra
      - doxygen
      - graphviz
      - python-numpy
      - gnuplot-nox
      - octave
      - gromacs-dev

env:
  global:
    - CMAKE_VERSION=3.1.3-Linux-x86_64
    - CCACHE_CPP2=yes

before_install:
  - git submodule update --init --recursive

before_script:
  - mkdir -p "$HOME/bin"
  - ln -s /usr/bin/ccache "$HOME/bin/clang++"
  - ln -s /usr/bin/ccache "$HOME/bin/clang"
# download newer cmake for gmx
  - wget --no-check-certificate -qO- http://www.cmake.org/files/v${CMAKE_VERSION:0:3}/cmake-${CMAKE_VERSION}.tar.gz | tar -xvz
  - ln -vs $PWD/cmake-${CMAKE_VERSION}/bin/cmake "$HOME/bin/cmake"
  - git clone --depth=1 --branch=global -b release-5-0 https://github.com/gromacs/gromacs.git &&
    cd gromacs && PATH="$HOME/bin:/usr/lib/ccache:$PATH" cmake -DCMAKE_INSTALL_PREFIX=$HOME/gromacs . && 
    make -j5 && make install && source $HOME/gromacs/bin/GMXRC.bash && cd ..

script:
  - mkdir build && cd build && 
    PATH="$HOME/bin:/usr/lib/ccache:$PATH" cmake -DBUILD_CSGAPPS=ON -DBUILD_CTP=ON -DBUILD_XTP=ON -DCMAKE_INSTALL_PREFIX=$HOME/votca .. &&
    make -j4 && make install

cache:
  directories:
    - $HOME/.ccache

compiler:
  - clang
  - gcc
