language: generic

sudo: required

services:
- docker

script:
 - docker build  --build-arg TRAVIS=${TRAVIS} --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH}
                 --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
                 --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
                 --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                 ${TRAVIS_TAG:+-t votca/votca:${TRAVIS_TAG}}
                 -t votca/votca:latest -t votca/votca:${TRAVIS_BRANCH} -f docker/votca docker/

after_success:
  - shopt -s extglob && [[ ${TRAVIS_BRANCH} = @(global|stable|v1.*) ]] && DEPLOY=yes
  - if [[ ${TRAVIS_BRANCH} = global ]]; then DOCKER_TAG=latest; else DOCKER_TAG="${TRAVIS_BRANCH}"; fi
  - if [[ ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${DEPLOY} ]]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push "votca/votca:${DOCKER_TAG}";
    fi


notifications:
  email:
    - votca-commits@googlegroups.com 
