name: 'Forward'
description: 'Forward commit to votca/votca'
inputs:
  module:
    description: 'VOTCA module to update'
    required: true
  token:
    description: 'GitHub token to use'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
