name: Docker
on:
  push:
    branches:
      - master
      - stable
    tags:
      - v[0-9]*
  pull_request:
    branches:
      - master
      - stable
  schedule:
    - cron:  '0 5 * * FRI'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code    
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
          path: votca
      - name: Build Docker images for Docker Hub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/votca
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: votca/.github/workflows/Dockerfile
          tag_with_ref: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
      - name: Build Docker images for Github Container Registry
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/votca
          registry: ghcr.io
          username: votca-bot
          password: ${{ secrets.VOTCA_BOT_TOKEN }}
          dockerfile: votca/.github/workflows/Dockerfile
          tag_with_ref: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
      - name: Build Docker images for Gitlab
        uses: docker/build-push-action@v1.1.0
        with:
          repository: votca/votca
          registry: registry.gitlab.com
          username: votca-bot
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
          dockerfile: votca/.github/workflows/Dockerfile
          tag_with_ref: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
