name: GPU

on:
  pull_request:
    branches:
      - master
      - stable

jobs:
  build:
    runs-on: [self-hosted, GPU, benchmark]

    steps:
      - name: cleanup
        run: rm -rf *
      - name: Checkout votca repo
        uses: actions/checkout@v2
        with:
          repository: votca/votca
          submodules: true
          ref: ${{ github.base_ref }}
          path: votca
          
      - name: Checkout xtp
        uses: actions/checkout@v2
        with:
          path: votca/xtp
          
      - name: Configure Cmake
        run: cmake -B builddir -DBUILD_CSGAPPS=ON -DBUILD_XTP=ON -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DUSE_CUDA=ON votca
        
      - name: Build
        run: cmake --build builddir --parallel 6
        
      - name: run Tests
        run: ctest --output-on-failure -j 6
        working-directory: builddir
      

        
      

